{{- range $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.global.appName }}-{{ $service.name }}-deployment
  namespace: {{ $.Values.global.appName }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.global.appName }}-{{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.global.appName }}-{{ $service.name }}
      annotations:
        redeploy-timestamp: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: {{ $.Values.global.appName }}-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ $service.name }}
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
          {{- range $key, $value := $service.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          ports:
            - name: port
              containerPort: {{ $service.port }}
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls"
              readOnly: true
            - name: data-volume
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: tls-certs
          secret:
            secretName: wildcard-tls-secret
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ $.Values.global.appName }}-pvc
---
{{- end }}
