{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.appName }}-{{ $service.name }}-service
  namespace: {{ $.Values.global.appName }}
spec:
  selector:
    app: {{ $.Values.global.appName }}-{{ $service.name }}
  ports:
  {{- if eq $service.name "server-postgres" }}
  - name: postgres
    port: {{ $service.port }}
    targetPort: {{ $service.port }}
  {{- else if eq $service.name "openfga" }}
  - name: openfga
    port: {{ $service.port }}
    targetPort: {{ $service.port }}
  {{- else }}
  - protocol: TCP
    port: 80
    targetPort: {{ $service.port }}
  {{- end }}
---
{{- end }}